### ISSUE TITLE
Request: Filter to exclude items from autotransfer regents

### ISSUE THREAD

**Issue by Nightfright** [Adirelle/AdiBags#25]
I like that my regents automatically gets moved to regenttab when visiting my bank
BUT I really really would like to be able to use a custom filter to exclude some items.
Cpl examples on what I would add to the filter is Fractured Temporal Crystal and Enchanting Vellum
both I like to keep in bags due to not being able to use them when they are in regent bank I need them on me.
I'm sure there are more examples on items one would like to exclude from the auto regent transfer.

**Comment by Adirelle** [comment]
AdiBags relies on the built-in deposit function to move the reagent to the reagent tab, and it doesn't accept any exception.
