### ISSUE TITLE
Request: show bank offline

### ISSUE THREAD

**Issue by d1masus** [Adirelle/AdiBags#26]
Hello and thanks for great addon.
Please consider adding ability to see cached bank contents of current character.
Thanks in advance and Happy new Year!
Dmitry

**Comment by d1masus** [comment]
It's too complex solution. I prefer use simple solutions for simple tasks. I don't need to see, what is stored in my alts bags, but ability to have a look what's in my current pers bank is very useful. tbag has this functionality, but it lacks support of newly added reagent part of bank.
Of course, it’s up to you as add-on author  :)

**Comment by Adirelle** [comment]
Implementing offline bank from something the only deals with "online" data is too complex, and I don't need that feature.
