### ISSUE TITLE
Copying profiles to second account

### ISSUE THREAD

**Issue by epicjaryn** [Adirelle/AdiBags#46]
I have two WoW accounts and I'd like to just copy my filters and setup (profile) from one account to the other. I can't seem to find where profiles are saved in the addon's directory or find a way to do this from the addon's interface options in-game.

**Comment by Adirelle** [comment]
You cannot do this in-game, for any addon. The profiles are stored in the WTF folder at the root of your game installation, in separate directories. This is not specific to AdiBags.

**Comment by ViddWizard** [comment]
I have two accounts and what you can do is this.

In the account 1 folder find "Saved Variables" (listed along with Realms names). Inside there find the two adibags files. (one is a backup). Copy both of those into the Saved Variables folder of your Second Account -- then in game do "load profile" and find the name of the character from account 1 you want to copy over. 

This is the only way I know to copy settings from one account to the other effectively.

**Comment by epicjaryn** [comment]
Thanks Vidd, that's exactly what I was looking for
