### ISSUE TITLE
Auc

### ISSUE THREAD

**Issue by F-I-R-E-F-O-X** [Adirelle/AdiBags#48]
11x ...aceTradeSkillMaster\Auction\AuctionFrame.lua:152: attempt to index field 'db' (a nil value)
...aceTradeSkillMaster\Auction\AuctionFrame.lua:152: in function `InitializeAuctionFrame'
...aceTradeSkillMaster\Auction\AuctionFrame.lua:214: in function `InitializeAHTab'
...aceTradeSkillMaster\Auction\AuctionFrame.lua:298: in main chunk

Locals:
self = <table> {
 ADDON_LOADED = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:284
 TabHidden = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:264
 RegisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterAllEvents = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 OnTabClick = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:240
 IsHooked = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:493
 PLAYER_MONEY = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:276
 UnregisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 InitializeAuctionFrame = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:150
 SecureHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 SendMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 SecureHookScript = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:410
 hooks = <table> {
 }
 IsTSMTab = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:197
 Hook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:274
 UnhookAll = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:477
 CreateTSMAHTab = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:28
 RegisterEvent = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterAllMessages = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 GetAuctionFrame = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:201
 RawHookScript = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:395
 AUCTION_HOUSE_SHOW = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:226
 HookScript = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:366
 queuedTabs = <table> {
 }
 RawHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:313
 Unhook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:418
 InitializeAHTab = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:209
 UnregisterEvent = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 auctionTabs = <table> {
 }
}
private = <table> {
 ADDON_LOADED = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:284
 TabHidden = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:264
 RegisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterAllEvents = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 OnTabClick = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:240
 IsHooked = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:493
 PLAYER_MONEY = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:276
 UnregisterMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 InitializeAuctionFrame = <function> defined @TradeSkillMaster\Auction\AuctionFrame.lua:150
 SecureHook = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:336
 SendMessage = <function> defined @AdiBags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:85
 SecureHookScript = <function> defined @AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:410
 hooks = <table> {
 }
 IsTSMTab =

**Comment by Adirelle** [comment]
Not related to AdiBags.
