### ISSUE TITLE
Level Up Causes Items to Move to "Recent Items" Section

### ISSUE THREAD

**Issue by thejames76** [Adirelle/AdiBags#53]
When leveling up, all items in my bag are moved into the Recent Items section.  There are a few items high-lighted in glowing green... the ones that actually ARE recent items, but everything else is up there without the glow.

The empty sections DO appear, however, they are completely empty. They do appear to have enough empty space in the section to accommodate the items that are now being shown in Recent Items.

I've attached a screen shot to illustrate (apparently I can't attach my screenshot... trying to fix).
![20-03-2015 1-39-52 pm](https://cloud.githubusercontent.com/assets/11576197/6757327/a0856194-cf06-11e4-9b0f-a5538ca8b1a1.jpg)

**Comment by Chorthee** [comment]
I just came here to post the same issue.  Everytime I level, on any character, all bag items go into recent items just like described.

**Comment by suricat89** [comment]
Same issue here too
